-- MySQL Script generated by MySQL Workbench
-- mar 21 mar 2023 15:45:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MAP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MAP` ;

-- -----------------------------------------------------
-- Schema MAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MAP` ;
USE `MAP` ;

-- -----------------------------------------------------
-- Table `MAP`.`Supermercados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MAP`.`Supermercados` ;

CREATE TABLE IF NOT EXISTS `MAP`.`Supermercados` (
  `idSupermercados` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSupermercados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MAP`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MAP`.`Productos` ;

CREATE TABLE IF NOT EXISTS `MAP`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `TiposS_idTiposS` INT NOT NULL,
  `Supermercados_idSupermercados` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Productos_TiposS_idx` (`TiposS_idTiposS` ASC) VISIBLE,
  INDEX `fk_Productos_Supermercados1_idx` (`Supermercados_idSupermercados` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_TiposS`
    FOREIGN KEY (`TiposS_idTiposS`)
    REFERENCES `MAP`.`TiposS` (`idTiposS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Productos_Supermercados1`
    FOREIGN KEY (`Supermercados_idSupermercados`)
    REFERENCES `MAP`.`Supermercados` (`idSupermercados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MAP`.`Etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MAP`.`Etiquetas` ;

CREATE TABLE IF NOT EXISTS `MAP`.`Etiquetas` (
  `idEtiquetas` INT NOT NULL AUTO_INCREMENT,
  `pasillo` INT NOT NULL,
  `estanteria` INT NOT NULL,
  `mapaFoto` VARCHAR(200) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Supermercados_idSupermercados` INT NOT NULL,
  PRIMARY KEY (`idEtiquetas`),
  UNIQUE INDEX `idEtiquetas_UNIQUE` (`idEtiquetas` ASC) VISIBLE,
  UNIQUE INDEX `mapaFoto_UNIQUE` (`mapaFoto` ASC) VISIBLE,
  INDEX `fk_Etiquetas_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Etiquetas_Supermercados1_idx` (`Supermercados_idSupermercados` ASC) VISIBLE,
  CONSTRAINT `fk_Etiquetas_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `MAP`.`Productos` (`idProductos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Etiquetas_Supermercados1`
    FOREIGN KEY (`Supermercados_idSupermercados`)
    REFERENCES `MAP`.`Supermercados` (`idSupermercados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MAP`.`Adiminstradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MAP`.`Adiminstradores` ;

CREATE TABLE IF NOT EXISTS `MAP`.`Adiminstradores` (
  `idAdiminstradores` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `tipo` ENUM("Cliente", "Trabajador") NOT NULL,
  `Supermercados_idSupermercados` INT NOT NULL,
  PRIMARY KEY (`idAdiminstradores`),
  UNIQUE INDEX `idAdiminstradores_UNIQUE` (`idAdiminstradores` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_Adiminstradores_Supermercados1_idx` (`Supermercados_idSupermercados` ASC) VISIBLE,
  CONSTRAINT `fk_Adiminstradores_Supermercados1`
    FOREIGN KEY (`Supermercados_idSupermercados`)
    REFERENCES `MAP`.`Supermercados` (`idSupermercados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `MAP`.`Supermercados`
-- -----------------------------------------------------
START TRANSACTION;
USE `MAP`;
INSERT INTO `MAP`.`Supermercados` (`idSupermercados`, `nombre`, `direccion`) VALUES (1, 'Eroski', 'Abando');
INSERT INTO `MAP`.`Supermercados` (`idSupermercados`, `nombre`, `direccion`) VALUES (2, 'Merkadona', 'San Mames');
INSERT INTO `MAP`.`Supermercados` (`idSupermercados`, `nombre`, `direccion`) VALUES (3, 'Lidl', 'Indautxu');
INSERT INTO `MAP`.`Supermercados` (`idSupermercados`, `nombre`, `direccion`) VALUES (4, 'Aldi', 'Sarriko');
INSERT INTO `MAP`.`Supermercados` (`idSupermercados`, `nombre`, `direccion`) VALUES (5, 'General', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MAP`.`Productos`
-- -----------------------------------------------------
START TRANSACTION;
USE `MAP`;
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (1, 'Lentejas', 0.99, '', 1, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (2, 'Dorada', 0.99, '', 1, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (3, 'Alubias ', 1.29, '', 1, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (4, 'Tomate', 1.19, '', 1, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (5, 'Pollo', 5.39, '', 2, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (6, 'Cerdo', 4.35, '', 2, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (7, 'Pavo', 7.5, '', 2, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (8, 'Ternera', 5.5, '', 2, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (9, 'Arroz', 1.2, '', 3, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (10, 'Quinoa', 1.4, '', 3, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (11, 'Espaguetis', 1.7, '', 3, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (12, 'Pan', 0.99, '', 3, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (13, 'Gulas', 6.0, '', 4, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (14, 'Sardinas', 4.5, '', 4, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (15, 'Lenguado', 5.0, '', 4, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (16, 'Bakalao', 7.0, '', 4, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (17, 'Macarrones', 1.5, '', 5, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (18, 'Fideos', 1.2, '', 5, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (19, 'Manzanas', 1.3, '', 5, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (20, 'Platanos', 1.4, '', 5, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (21, 'Peras', 5.0, '', 6, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (22, 'Lejia', 6.0, '', 6, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (23, 'Champu', 3.0, '', 6, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (24, 'Gel', 1.5, '', 6, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (25, 'Leche', 0.3, '', 7, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (26, 'Zumo', 1.5, '', 7, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (27, 'Yogures', 2.0, '', 7, 1);
INSERT INTO `MAP`.`Productos` (`idProductos`, `nombre`,  `precio`, `imagen`, `TiposS_idTiposS`, `Supermercados_idSupermercados`) VALUES (28, 'Kas', 1.99, '', 7, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `MAP`.`Adiminstradores`
-- -----------------------------------------------------
START TRANSACTION;
USE `MAP`;
INSERT INTO `MAP`.`Adiminstradores` (`idAdiminstradores`, `login`, `contraseña`, `nombre`, `apellido`, `DNI`, `correo`, `tipo`, `Supermercados_idSupermercados`) VALUES (1, 'sjurado', 'sjurado', 'Sara', 'Jurado', '', '', 'Cliente', 1);
INSERT INTO `MAP`.`Adiminstradores` (`idAdiminstradores`, `login`, `contraseña`, `nombre`, `apellido`, `DNI`, `correo`, `tipo`, `Supermercados_idSupermercados`) VALUES (2, 'prodriguez', 'prodriguez', 'Paula', 'Rodriguez', '', '', 'Trabajador', 1);

COMMIT;
